minimumReleaseAge: 1440

overrides:
  date-fns: 3.6.0

ignoredBuiltDependencies:
  - '@clerk/shared'
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - duckdb
  - esbuild
  - msw

allowBuilds:
  '@clerk/shared': false
  duckdb: true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true
