ignoredBuiltDependencies:
  - '@clerk/shared'
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - duckdb
  - esbuild
  - msw

patchedDependencies:
  apache-arrow@17.0.0: patches/apache-arrow@17.0.0.patch
