export { default as IconDiscord } from "./icon-discord";
export { default as IconDocker } from "./icon-docker";
export { default as IconFacebook } from "./icon-facebook";
export { default as IconFigma } from "./icon-figma";
export { default as IconGithub } from "./icon-github";
export { default as IconGitlab } from "./icon-gitlab";
export { default as IconGmail } from "./icon-gmail";
export { default as IconMedium } from "./icon-medium";
export { default as IconNotion } from "./icon-notion";
export { default as IconSkype } from "./icon-skype";
export { default as IconSlack } from "./icon-slack";
export { default as IconStripe } from "./icon-stripe";
export { default as IconTelegram } from "./icon-telegram";
export { default as IconTrello } from "./icon-trello";
export { default as IconWhatsapp } from "./icon-whatsapp";
export { default as IconZoom } from "./icon-zoom";
export { IconDiscord } from "./icon-discord";
export { IconFacebook } from "./icon-facebook";
export { IconFigma } from "./icon-figma";
export { IconGithub } from "./icon-github";
export { IconGitlab } from "./icon-gitlab";
export { IconGmail } from "./icon-gmail";
export { IconMedium } from "./icon-medium";
export { IconNotion } from "./icon-notion";
export { IconSkype } from "./icon-skype";
export { IconSlack } from "./icon-slack";
export { IconStripe } from "./icon-stripe";
export { IconTelegram } from "./icon-telegram";
export { IconTrello } from "./icon-trello";
export { IconWhatsapp } from "./icon-whatsapp";
export { IconZoom } from "./icon-zoom";
