import { Project } from "ts-morph";
import { writeFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import { glob } from "glob";
import path from "path";

async function sync() {
  const project = new Project();
  
  // 1. Freshly scan the directory
  const componentFiles = await glob("components/ui/**/*.tsx");
  
  const definitions: string[] = [];
  const imports: string[] = [];
  const processedNames = new Set<string>();

  if (!existsSync('lib/ui-builder/registry')) {
    await mkdir('lib/ui-builder/registry', { recursive: true });
  }

  for (const file of componentFiles) {
    // 2. HARD CHECK: Does the file actually exist on the disk right now?
    if (!existsSync(file)) {
        console.log(`Skipping non-existent file: ${file}`);
        continue;
    }

    const fileName = path.basename(file, ".tsx");
    const pascalName = fileName
      .split(/[-_]/)
      .map(p => p.charAt(0).toUpperCase() + p.slice(1))
      .join("");

    // Skip utility files
    if (['index', 'utils', 'types', 'schema'].includes(fileName)) continue;

    const sourceFile = project.addSourceFileAtPath(file);
    const exportedDeclarations = sourceFile.getExportedDeclarations();
    
    // 3. EXPORT CHECK: Only import if the file actually HAS the component
    const isNamedExport = exportedDeclarations.has(pascalName);
    const hasDefaultExport = exportedDeclarations.has("default");

    if (!isNamedExport && !hasDefaultExport) continue;

    if (processedNames.has(pascalName)) continue;
    processedNames.add(pascalName);

    // 4. Generate the correct import style
    const importPath = `@/components/ui/${fileName}`;
    const importLine = isNamedExport 
      ? `import { ${pascalName} } from "${importPath}";`
      : `import ${pascalName} from "${importPath}";`;

    imports.push(importLine);
    
    definitions.push(`
  ${pascalName}: {
    component: ${pascalName},
    schema: z.object({
      className: z.string().optional(),
    }),
    from: "${importPath}",
  }`);
  }

  const content = `/* eslint-disable @typescript-eslint/no-explicit-any */
// AUTOMATICALLY GENERATED - DO NOT EDIT
import { z } from "zod";
${imports.join("\n")}

export const autoGeneratedDefinitions: Record<string, any> = {
${definitions.join(",\n")}
};`;

  await writeFile("lib/ui-builder/registry/auto-generated.ts", content);
  console.log(`✅ Success! Synced ${processedNames.size} components. Any missing files were ignored.`);
}

sync().catch(console.error);